export enum ACTIONS {
  ADD_ITEM = "ADD_ITEM",
  REMOVE_ALL_ITEMS = "REMOVE_ALL_ITEMS",
  REMOVE_ITEM = "REMOVE_ITEM",
  INCREMENT_ITEM = "INCREMENT_ITEM",
  UPDATE_ITEM = "UPDATE_ITEM",
  CLEAR_CART = "CLEAR_CART",
}
